### PR TITLE
visibility fix

### PR DESCRIPTION
**Pull request by juliavi**
fixing the visibility error

### CODE REVIEW

**Comment by ccfiel** [comment]
why this it not merge to the master? this is the solution of the problem in lecture 16.

**Comment by acloudfan** [comment]
Hi Chris,
I apologize .... I thought I took care of this issue .. let me check.

Regards, Raj

**Comment by acloudfan** [comment]
Hi Chris,
thanks for pointing it out .... somehow missed it .... its done now.

Best Regards, Raj

**Comment by ccfiel** [comment]
No worries! :)

**Pull request merged**
